connections = [("Piran", "Koper"),
               ("Koper", "Postojna"),
               ("Ilirska Bistrica", "Postojna"),
               ("Postojna", "Logatec"), ("Postojna", "Cerknica"),
               ("Gorica", "Ajdovščina"), ("Gorica", "Bled"), ("Gorica", "Jesenice"),
               ("Ajdovščina", "Postojna"),
               ("Idrija", "Logatec"), ("Idrija", "Žiri"),
               ("Logatec", "Žiri"), ("Logatec", "Vrhnika"), ("Logatec", "Cerknica"),
               ("Cerknica", "Ribnica"),
               ("Vrhnika", "Ljubljana"),
               ("Žiri", "Škofja Loka"),
               ("Ljubljana", "Škofja Loka"), ("Ljubljana", "Kamnik"),
               ("Ljubljana", "Celje"), ("Ljubljana", "Litija"),
               ("Ljubljana", "Grosuplje"), ("Ljubljana", "Kranj"),
               ("Ribnica", "Grosuplje"), ("Ribnica", "Kočevje"),
               ("Kočevje", "Novo mesto"),
               ("Grosuplje", "Novo mesto"),
               ("Litija", "Trbovlje"),
               ("Kranj", "Bled"), ("Kranj", "Škofja Loka"), ("Kranj", "Kamnik"),
               ("Kamnik", "Velenje"), ("Kamnik", "Celje"), ("Kamnik", "Škofja Loka"),
               ("Trbovlje", "Celje"), ("Trbovlje", "Krško"),
               ("Novo mesto", "Krško"),
               ("Krško", "Ptuj"),
               ("Celje", "Velenje"), ("Celje", "Slovenska Bistrica"),
               ("Maribor", "Slovenska Bistrica"), ("Maribor", "Ptuj"),
               ("Maribor", "Murska Sobota"), ("Maribor", "Ljutomer"),
               ("Velenje", "Slovenska Bistrica"),
               ("Slovenska Bistrica", "Ptuj"),
               ("Murska Sobota", "Gornja Radgona"), ("Murska Sobota", "Ljutomer"),
               ("Ptuj", "Ormož"),
               ("Ljutomer", "Ormož"),
               ("Bled", "Jesenice")]

places_coords = {'Cerknica': (235, 328), 'Krško': (547, 253), 'Celje': (445, 178), 'Maribor': (528, 63),
                 'Škofja Loka': (215, 198), 'Grosuplje': (303, 271), 'Koper': (75, 414), 'Idrija': (153, 260),
                 'Ormož': (648, 116), 'Postojna': (192, 333), 'Žiri': (170, 236), 'Kranj': (228, 171),
                 'Kočevje': (340, 377), 'Bled': (192, 133), 'Vrhnika': (223, 268), 'Ribnica': (317, 342),
                 'Ljutomer': (659, 79), 'Velenje': (409, 134), 'Litija': (341, 236), 'Gornja Radgona': (613, 13),
                 'Logatec': (198, 281), 'Piran': (51, 426), 'Jesenice': (156, 90), 'Ajdovščina': (125, 294),
                 'Murska Sobota': (651, 16), 'Ljubljana': (258, 235), 'Novo mesto': (414, 322),
                 'Ilirska Bistrica': (202, 405), 'Gorica': (55, 276), 'Ptuj': (580, 109),
                 'Slovenska Bistrica': (510, 126), 'Trbovlje': (393, 206), 'Kamnik': (288, 178)}
