cities = \
    {
    "Piran": {"Koper"},
    "Koper": {"Postojna", "Piran"},
    "Postojna": {"Cerknica", "Logatec", "Koper", "Ajdovščina", "Ilirska Bistrica"},
    "Ilirska Bistrica": {"Postojna"},
    "Logatec": {"Cerknica", "Idrija", "Postojna", "Vrhnika", "Žiri"},
    "Cerknica": {"Postojna", "Logatec", "Ribnica"},
    "Gorica": {"Bled", "Ajdovščina", "Jesenice"},
    "Ajdovščina": {"Postojna", "Gorica"},
    "Bled": {"Gorica", "Kranj", "Jesenice"},
    "Jesenice": {"Gorica", "Bled"},
    "Idrija": {"Logatec", "Žiri"},
    "Žiri": {"Škofja Loka", "Logatec", "Idrija"},
    "Vrhnika": {"Ljubljana", "Logatec"},
    "Ribnica": {"Grosuplje", "Cerknica", "Kočevje"},
    "Ljubljana": {"Kamnik", "Kranj", "Litija", "Grosuplje", "Škofja Loka", "Vrhnika", "Celje"},
    "Škofja Loka": {"Ljubljana", "Kamnik", "Kranj", "Žiri"},
    "Kamnik": {"Ljubljana", "Kranj", "Škofja Loka", "Velenje", "Celje"},
    "Celje": {"Ljubljana", "Slovenska Bistrica", "Kamnik", "Trbovlje", "Velenje"},
    "Litija": {"Ljubljana", "Trbovlje"},
    "Grosuplje": {"Ljubljana", "Ribnica", "Novo mesto"},
    "Kranj": {"Ljubljana", "Škofja Loka", "Kamnik", "Bled"},
    "Kočevje": {"Ribnica", "Novo mesto"},
    "Novo mesto": {"Grosuplje", "Kočevje", "Krško"},
    "Trbovlje": {"Krško", "Celje", "Litija"},
    "Velenje": {"Slovenska Bistrica", "Kamnik", "Celje"},
    "Krško": {"Ptuj", "Novo mesto", "Trbovlje"},
    "Ptuj": {"Slovenska Bistrica", "Krško", "Maribor", "Ormož"},
    "Slovenska Bistrica": {"Ptuj", "Velenje", "Maribor", "Celje"},
    "Maribor": {"Ptuj", "Slovenska Bistrica", "Murska Sobota", "Ljutomer"},
    "Murska Sobota": {"Gornja Radgona", "Maribor", "Ljutomer"},
    "Ljutomer": {"Murska Sobota", "Maribor", "Ormož"},
    "Gornja Radgona": {"Murska Sobota"},
    "Ormož": {"Ptuj", "Ljutomer"}
    }

countries = \
    {
    "Slovenia": {"Austria", "Italy", "Croatia", "Hungary"},
    "Croatia": {"Slovenia", "Hungary", "Serbia", "Bosnia and Herzegovina", "Montenegro"},
    "Italy": {"Austria", "France", "Holy See", "San Marino", "Slovenia", "Switzerland"},
    "Austria": {"Germany", "Czech Republic", "Slovakia", "Poland", "Hungary", "Slovenia", "Switzerland"},
    "France": {"Belgium", "Luxembourg", "Germany", "Switzerland", "Italy", "Spain", "Andorra"},
    "Serbia": {"Hungary", "Romania", "Bulgaria", "Macedonia", "Montenegro", "Bosnia and Herzegovina", "Croatia", "Kosovo"},
    "Bosnia and Herzegovina": {"Croatia", "Serbia", "Montenegro"},
    "Germany": {"Netherlands", "Belgium", "Luxembourg", "France", "Switzerland", "Austria", "Czech Republic", "Poland", "Denmark"},
    "Netherlands": {"Belgium", "Germany"},
    "Belgium": {"Netherlands", "Luxembourg", "France", "Germany"},
    "Spain": {"Andorra", "France", "Portugal"},
    "Hungary": {"Slovakia", "Austria", "Croatia", "Ukraine", "Serbia", "Romania", "Slovenia"},
    "Holy See": {"Italy"},
    "San Marino": {"Italy"},
    "Switzerland": {"Austria", "Italy", "France", "Germany"},
    "Czech Republic": {"Poland", "Slovakia", "Austria", "Germany"},
    "Slovakia": {"Czech Republic", "Ukraine", "Poland", "Austria", "Hungary"},
    "Poland": {"Belarus", "Ukraine", "Slovakia", "Czech Republic", "Germany", "Lithuania"},
    "Luxembourg": {"Belgium", "Germany", "France"},
    "Andorra": {"Spain", "France"},
    "Portugal": {"Spain"},
    "Lithuania": {"Belarus", "Latvia", "Poland"},
    "Ukraine": {"Russia", "Moldova", "Romania", "Slovakia", "Hungary", "Poland", "Belarus"},
    "Denmark": {"Germany", "Sweden"},
    "Romania": {"Moldova", "Ukraine", "Bulgaria", "Serbia", "Hungary"},
    "Latvia": {"Estonia", "Lithuania", "Russia", "Belarus"},
    "Estonia": {"Russia", "Latvia"},
    "Russia": {"Finland", "Latvia", "Estonia", "Belarus", "Ukraine"},
    "Belarus": {"Russia", "Lithuania", "Latvia", "Ukraine", "Poland"},
    "Moldova": {"Romania", "Ukraine"},
    "Bulgaria": {"Romania", "Serbia", "Macedonia", "Greece", "Turkey"},
    "Kosovo": {"Montenegro", "Serbia", "Macedonia", "Albania"},
    "Montenegro": {"Croatia", "Bosnia and Herzegovina", "Serbia", "Albania", "Kosovo"},
    "Macedonia": {"Bulgaria", "Albania", "Greece", "Serbia", "Kosovo"},
    "Greece": {"Turkey", "Albania", "Macedonia", "Bulgaria"},
    "Turkey": {"Greece", "Bulgaria"},
    "Albania": {"Montenegro", "Kosovo", "Macedonia", "Greece"},
    "Finland": {"Russia", "Norway", "Sweden"},
    "Norway": {"Russia", "Finland", "Sweden"},
    "Sweden": {"Norway", "Finland", "Denmark"}
    }

cities_coords = \
    {
        'Cerknica': (235, 328),
        'Krško': (547, 253),
        'Celje': (445, 178),
        'Maribor': (528, 63),
        'Škofja Loka': (215, 198),
        'Grosuplje': (303, 271),
        'Koper': (75, 414),
        'Idrija': (153, 260),
        'Ormož': (648, 116),
        'Postojna': (192, 333),
        'Žiri': (170, 236),
        'Kranj': (228, 171),
        'Kočevje': (340, 377),
        'Bled': (192, 133),
        'Vrhnika': (223, 268),
        'Ribnica': (317, 342),
        'Ljutomer': (659, 79),
        'Velenje': (409, 134),
        'Litija': (341, 236),
        'Gornja Radgona': (613, 13),
        'Logatec': (198, 281),
        'Piran': (51, 426),
        'Jesenice': (156, 90),
        'Ajdovščina': (125, 294),
        'Murska Sobota': (651, 16),
        'Ljubljana': (258, 235),
        'Novo mesto': (414, 322),
        'Ilirska Bistrica': (202, 405),
        'Gorica': (55, 276),
        'Ptuj': (580, 109),
        'Slovenska Bistrica': (510, 126),
        'Trbovlje': (393, 206),
        'Kamnik': (288, 178)
    }

countries_coords = \
    {
        'Andorra': (246, 683),
        'Turkey': (743, 755),
        'Switzerland': (367, 598),
        'Albania': (566, 736),
        'Moldova': (688, 573),
        'San Marino': (435, 674),
        'Latvia': (606, 365),
        'Ukraine': (701, 504),
        'Luxembourg': (343, 531),
        'Montenegro': (548, 697),
        'Croatia': (494, 633),
        'Italy': (402, 643),
        'Spain': (151, 707),
        'Hungary': (539, 597),
        'Belgium': (324, 505),
        'Romania': (635, 616),
        'Kosovo': (576, 705),
        'Slovakia': (540, 557),
        'Holy See': (431, 718),
        'Estonia': (603, 320),
        'Belarus': (653, 438),
        'Macedonia': (592, 718),
        'Greece': (607, 783),
        'Austria': (468, 588),
        'Netherlands': (342, 472),
        'Czech Republic': (477, 535),
        'Serbia': (565, 647),
        'Slovenia': (472, 622),
        'Sweden': (477, 290),
        'Bulgaria': (648, 690),
        'Norway': (409, 281),
        'Portugal': (60, 711),
        'Lithuania': (593, 399),
        'Bosnia and Herzegovina': (520, 664),
        'France': (271, 569),
        'Germany': (404, 493),
        'Poland': (535, 478),
        'Denmark': (406, 383),
        'Russia': (826, 309),
        'Finland': (598, 208)
    }